package com.example.fe_prm.apiservices.bookingreservations;

import com.example.fe_prm.models.DesiredReservation;
import com.example.fe_prm.models.VacantTable;

import retrofit2.Call;
import retrofit2.http.Body;
import retrofit2.http.Headers;
import retrofit2.http.POST;

public interface BookingReservationService {
    String BOOKING_RESERVATION = "/api/booking-reservation"; // API endpoint
    String tempJWT = "eyJhbGciOiJSUzI1NiIsImtpZCI6IjY3NmRhOWQzMTJjMzlhNDI5OTMyZjU0M2U2YzFiNmU2NTEyZTQ5ODMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJuYmYiOjE2ODk1OTc1MzYsImF1ZCI6IjI0NzAyMjkwMDI3NS0zZWx0ZGtuMXZtYTIwbDNwcjYxamZudnBhNGs4Ymdlby5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsInN1YiI6IjEwMTM3MTM4NjM2MjgyNzM1ODkxOCIsImVtYWlsIjoiZGF0bHQubWRjQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhenAiOiIyNDcwMjI5MDAyNzUtM2VsdGRrbjF2bWEyMGwzcHI2MWpmbnZwYTRrOGJnZW8uYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJuYW1lIjoiVGjDoG5oIMSQ4bqhdCBMw6oiLCJwaWN0dXJlIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUFjSFR0Y0dHUktIV0FNWnNwYlVFWjhVZ0FLMl9NY2tSbEVPem1uajM3eFZSZlN2dnc9czk2LWMiLCJnaXZlbl9uYW1lIjoiVGjDoG5oIMSQ4bqhdCIsImZhbWlseV9uYW1lIjoiTMOqIiwiaWF0IjoxNjg5NTk3ODM2LCJleHAiOjE2ODk2MDE0MzYsImp0aSI6IjMyZWRjNDZmOGU0OTdhNDRjZGEwYjljOWMxOWRlNGQ0ZjNjMjYxMDUifQ.Bg_ZHgfWYI00GtuDRzFuzjZngagML7xGg2rThU_21bWkI8TigDXYTcZu1D-CNRsARju6o2iJeD5VBGt9GltIUPAk13p9V0aHeN9BMEdd6M9U8mqr7crrlO2a28lDI9Wy9n3ukIX7aMqfqWZDPYdfmCglV6al4XqbFa10zqLJdFHimD2PCbYxrtXPah0zAvW3I6lCzc5UQ-92SSXbrCi909ivqymVSCEZgyYot1DDD6vWIzY-7v--2RGdBjLgvsPM5cbZZT4Axoqn-_hVoFrVFqpLVWOfsiufqdBw2V34fMA_jNDqez7MTr3axNx22NEe9IkGK4SKKrrv1Ze9HHwbpg";

    //@GET(BOOKING_RESERVATION + )
    @POST(BOOKING_RESERVATION + "/vacant-amount")
    @Headers("Authorization: Bearer " + tempJWT)
    Call<VacantTable[]> getVacantTables(@Body DesiredReservation desiredReservation);


}
